image: pedramrn/java-gradle:with-compose

services:
- docker:dind

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - gradle clean assemble
  cache:
    paths:
      - build
      - app/build
  artifacts:
    paths:
      - build/
      - app/build

test_job:
  stage: test
  script:
    - gradle test
  cache:
    paths:
      - app/build
  artifacts:
    paths:
      - app/build

deploy_job:
  image: docker:latest
  stage: deploy
#  only:
#    - master
  script:
    - ls -la app/build/libs
    - docker build -f app/src/main/docker/Dockerfile -t pedramrn/webapp:latest .
