image: pedramrn/java-gradle:with-compose

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - build
    - app/build
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - gradle clean bootRepackage
  artifacts:
    paths:
      - app/build/libs

#test_job:
#  stage: test
#  script:
#    - gradle test
#  artifacts:
#    paths:
#      - app/build/libs

deploy_job:
#  variables:
#    BUILD_IMAGE: pedramrn/webapp:latest
#  image: pedramrn/docker-buidler:3
#    image: docker:latest
  stage: deploy
#  only:
#    - master
  script:
    - docker-compose -f docker-compose-prod.yml pull
    - docker-compose -f docker-compose-prod.yml build
    - docker-compose -f docker-compose-prod.yml up

after_script:
  - docker-compose -f docker-compose-prod.yml down
#      - docker build -f app/src/main/docker/Dockerfile -t pedramrn/webapp:latest .
