stages:
  - build_test
  - deploy

build_test_job:
  stage: build_test
  script:
    - docker run --rm --name test-runner -v ~/.m2:/root/.m2 -v ~/.gradle:/root/.gradle -v $PWD:/src -w /src pedramrn/java-gradle:oracle-8-gradle-2.10 gradle clean build
  artifacts:
    paths:
      - app/build/libs/*.jar
    downloadable: false

deploy_job:
  stage: deploy
  only:
    - tags
    - master
  except:
    - branches
  script:
    - docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker build -f app/src/main/docker/Dockerfile -t pedramrn/webapp:$CI_BUILD_TAG .
    - docker push pedramrn/webapp:$CI_BUILD_TAG
