image: pedramrn/java-gradle:with-compose

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - gradle clean assemble

test_job:
  stage: test
  script:
    - gradle test

deploy_job:
  image: docker:latest
  stage: deploy
#  only:
#    - master
  script:
    - docker build -f app/src/main/docker/Dockerfile -t pedramrn/webapp:latest .
