stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - docker run --rm --name test-runner -v ~/.m2:/root/.m2 -v ~/.gradle:/root/.gradle -v $PWD:/src -w /src pedramrn/java-gradle:oracle-8-gradle-2.10 gradle build
  artifacts:
    paths:
      - app/build/libs

#test_job:
#  stage: test
#  script:
#    - gradle test
#  artifacts:
#    paths:
#      - app/build/libs

deploy_job:
#  variables:
#    BUILD_IMAGE: pedramrn/webapp:latest
#  image: pedramrn/docker-buidler:3
#    image: docker:latest
  stage: deploy
#  only:
#    - master
  script:
      - docker build -f app/src/main/docker/Dockerfile -t pedramrn/webapp:latest .
#    - docker-compose -f docker-compose-prod.yml pull
#    - docker build -f app/src/main/docker/Dockerfile -t
#    - docker-compose -f docker-compose-prod.yml up

