image: pedramrn/java-gradle:with-compose

services:
- docker:dind

cache:
  paths:
    - build
    - app/build

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - gradle clean bootRepackage
  artifacts:
    paths:
      - app/build/libs

#test_job:
#  stage: test
#  script:
#    - gradle test
#  artifacts:
#    paths:
#      - app/build/libs

deploy_job:
  variables:
    BUILD_IMAGE: pedramrn/webapp:latest
  image: pedramrn/docker-buidler:3
#    image: docker:latest
  stage: deploy
#  only:
#    - master
  script:
    - docker info
    - ls -la app/build/libs
    - docker run pedramrn/docker-buidler:3 --name fooBar
#      - docker build -f app/src/main/docker/Dockerfile -t pedramrn/webapp:latest .
