version: '2'
services:
  app:
    image: pedramrn/java-gradle:oracle-8-gradle-2.10
    container_name: app
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ~/.m2:/root/.m2
      - ~/.gradle:/root/.gradle
      - .:/src
    networks:
      - main
    working_dir: /src
    environment:
      - GRADLE_VERSION=2.10
    command: gradle bootRun
#        restart: always
    depends_on:
      - db-postgresql

  db-postgresql:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - data-postgresql:/var/lib/postgresql/data
    networks:
      - main
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres

volumes:
  data-postgresql:

networks:
  main:
