version: '2'
services:
  app:
    build:
      context: .
      dockerfile: app/src/main/docker/Dockerfile
    image: pedramrn/webapp
    container_name: app
    ports:
      - "80:8080"
    networks:
      - main
    working_dir: /src
    restart: always
    depends_on:
      - db-postgresql
      - db-mongo

  db-postgresql:
    image: postgres:9.5
    container_name: db-postgresql
    ports:
      - "5432:5432"
    volumes:
      - data-postgresql:/var/lib/postgresql/data
    networks:
      - main
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres

  db-mongo:
    image: mongo:3.2
    container_name: db-mongo
    ports:
      - "27017:27017"
    volumes:
      - data-mongo:/data/db
    networks:
      - main
    restart: always

volumes:
  data-mongo:

  data-postgresql:

  data-maven:

  data-gradle:

networks:
  main:
