spring:
  profiles:
    active: dev
---

spring:
  profiles: test
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://db-postgresql:5432/postgres
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://db-postgresql:5432/postgres
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate